 service: lambda-probot-express

 provider:
   name: aws
   runtime: nodejs8.10
   region: us-east-1

 functions:
   router:
     handler: handler.probot

     environment:
       # replace values with one\'s associated to your app
       APP_ID: ${param:APP_ID}
       PRIVATE_KEY: ${param:PRIVATE_KEY}
       WEBHOOK_SECRET: ${param:WEBHOOK_SECRET}
       LOG_FORMAT: json 

     events:
       - http:
          path: /probot
          method: post